repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies:
          - commitlint-plugin-function-rules
          - '@commitlint/config-conventional'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: gen-proto
        name: gen-proto
        language: golang
        entry: make gen-proto
      - id: gen-gateway
        name: gen-gateway
        language: golang
        entry: make gen-gateway
      - id: gen-openapi
        name: gen-openapi
        language: golang
        entry: make gen-openapi
